### ISSUE TITLE
iam:* InvalidClientTokenId

### ISSUE THREAD

**Issue by joekiller** [awslabs/amazon-ecs-local-container-endpoints#11]
I cannot perform iam:* commands (I tried create-role, delete-role, or list-groups) when the request is signed by a token issued by my ecs-local-container-endpoints via `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/creds` 

I first encountered this using AWS SDK for Java 1.11.551 and then replicated it on aws-cli/1.16.148. I'm using endpoints 1.0.1 but 1.0.0 didn't work either.

Steps to reproduce using aws-cli/1.16.158 Python/3.6.8 Linux/5.0.13-arch1-1-ARCH botocore/1.12.148 are as follows:
```
# setup ~/.aws
aws configure

# verify role creation works with standard policy
 aws iam create-role --role-name joe-test --assume-role-policy-document '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":["ec2.amazonaws.com"]},"Action":["sts:AssumeRole"]}]}'

# break local .aws and enable ecs endpoints
mv ~/.aws ~/.aws-nope
export AWS_DEFAULT_REGION=us-east-1
export AWS_REGION=us-east-1
export AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/creds
docker run -d -p 51679:51679 -v /var/run:/var/run -v $HOME/.aws-nope/:/home/.aws/ -e "ECS_LOCAL_METADATA_PORT=51679" --name ecs-local-endpoints amazon/amazon-ecs-local-container-endpoints:latest

# verifiy token service is working
aws s3 ls

# create a new role but it's busted
aws iam create-role --role-name joe-test-broken --assume-role-policy-document '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":["ec2.amazonaws.com"]},"Action":["sts:AssumeRole"]}]}'

An error occurred (InvalidClientTokenId) when calling the CreateRole operation: The security token included in the request is invalid

# cannot delete other role
aws iam delete-role --role-name joe-test

An error occurred (InvalidClientTokenId) when calling the DeleteRole operation: The security token included in the request is invalid

# fix the cli
mv ~/.aws-nope ~/.aws

# delete the example role
aws iam delete-role --role-name joe-test
```

Running it in debug the response was:
> 2019-05-14 21:47:11,248 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': '5b2f97bc-76b3-11e9-95f1-97b56e28630b', 'Content-Type': 'text/xml', 'Content-Length': '305', 'Date': 'Wed, 15 May 2019 01:47:11 GMT'}
> 2019-05-14 21:47:11,248 - MainThread - botocore.parsers - DEBUG - Response body:
b'<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>InvalidClientTokenId</Code>\n    <Message>The security token included in the request is invalid</Message>\n  </Error>\n  <RequestId>5b2f97bc-76b3-11e9-95f1-97b56e28630b</RequestId>\n</ErrorResponse>\n'

I found this because my local CodeBuild was failing. I pulled a wire debug from a local build and compared it to the wire on CodeBuild and the requests look good.

| Environment | amz-sdk-invocation-id | x-amzn-RequestId | Result
| -------------- | ------------------------ | --------------------- | -------
ECS Endpoints | `71988628-acf5-0d1b-b341-9382c38a7e93` | `076d4513-767a-11e9-89db-c3541b5d08ec` | InvalidClientTokenId
CodeBuild | `00e8eab6-44c2-1126-224e-d5c9772e105f` | `fab50e20-7688-11e9-9527-27af0247c969` | Success (CreateRoleResponse)

**Comment by PettitWesley** [comment]
@joekiller Check out the entry for [sts:GetSessionToken in the STS API Comparison](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#stsapi_comparison).

The `/creds` path uses sts:GetSessionToken, and it has some limitations. As stated in the STS docs,

> Cannot call IAM API operations unless MFA information is included with the request.

> Cannot call AWS STS API operations except AssumeRole or GetCallerIdentity.

If you set `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/role/{role name}` you can assume an IAM role in your container. You can allow that IAM role allows access to the IAM APIs.

**Comment by joekiller** [comment]
Okay thanks!
