### ISSUE TITLE
Empty Expiration Redux

### ISSUE THREAD

**Issue by dacut** [awslabs/amazon-ecs-local-container-endpoints#26]
Same issue as here https://github.com/awslabs/amazon-ecs-local-container-endpoints/issues/23

This is path 1b (grabbing a temporary credential and stashing it in `~/.aws/credentials`) from issue #23 -- it makes Boto unhappy.

Retrieving the credentials, as @PettitWesley alludes to, doesn't include an expiration date because this isn't a thing in `~/.aws/credentials`:
```
% curl http://169.254.170.2/creds
{"AccessKeyId":"ASIA----------EGKVOM","Expiration":"","RoleArn":"","SecretAccessKey":"4su0....","Token":"FQoG...."}
```

Boto barfs on the empty `Expiration` field:
```
# export AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/creds
# python3                       
Python 3.7.4 (default, Jul 30 2019, 19:56:38) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> boto3.__version__
'1.9.246'
>>> boto3.client("ssm")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 827, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 426, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1934, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1797, in load
    return self._retrieve_or_fail()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1812, in _retrieve_or_fail
    expiry_time=_parse_if_needed(creds['expiry_time']),
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 196, in _parse_if_needed
    return parse(value)
  File "/usr/local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1358, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 652, in parse
    raise ValueError("String does not contain a date:", timestr)
ValueError: ('String does not contain a date:', '')
```

My suggestion is to include `expiration` as a valid field in the `~/.aws/credentials` file -- it really ought to be there for temporary credentials like this.

I'm fairly certain the session token does include an expiration date in there, but it's not for consumption outside of the AWS Auth service. (I'm fairly certain it's encrypted, and if we could decrypt it anyone could also go about generating secret keys and session tokens, which would be... bad. The Auth team would know for sure, though.)

**Comment by dacut** [comment]
FWIW, Boto3 is also unhappy if you exclude the Expiration header entirely (which I tested with my own hacked-together server):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 827, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 426, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1934, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1797, in load
    return self._retrieve_or_fail()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1806, in _retrieve_or_fail
    creds = fetcher()
  File "/usr/local/lib/python3.7/site-packages/botocore/credentials.py", line 1838, in fetch_creds
    'expiry_time': response['Expiration'],
KeyError: 'Expiration'
```

**Comment by PettitWesley** [comment]
I think the fastest way to solve this for local container endpoints would be to set a false expiration. Set it to be only a few minutes in the future- that way is very likely its less than the actual expiration. Every time the fake expiration hits, I think the SDKs will auto-request for new credentials, and local endpoints can just return the same set of credentials with an new fake expiration. 

We should probably check how the SDK actually works. If it makes a request that fails because its credentials are expired, what does it do? If it tries to refresh its set of credentials automatically, then local container endpoints could set a fake expiration which is far in the future- since whenever they actually expire and an API request fails the SDK will handle it by refreshing them (making a request to local container endpoints).

**Comment by dacut** [comment]
I'll get back to you on this: "If it makes a request that fails because its credentials are expired, what does it do?"

I know I've seen requests fail outright due to expired credentials, but that was in cases where Boto isn't instantiating a refreshing provider (the creds are coming in through environment variables). There's a fair bit of automagic happening in the guts of Boto here, depending on how it detects credentials are being provided. (You can, obviously, specify the provider explicitly, but nobody does that; it ties you to a specific environment.)

**Comment by dacut** [comment]
On:  "If it makes a request that fails because its credentials are expired, what does it do?"
Answer: Nothing good. It just returns an exception to the client without refreshing the credentials or retrying the operation.

`Exception: An error occurred (ExpiredToken) when calling the ListBuckets operation: The provided token has expired.`

However, take a look at this: https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L336
Boto has interesting default behavior if the expiration of the current set of refreshable credentials is less than or equal to 15 minutes but greater than 10 minutes in the future, refreshing without blocking other threads. If it is 10 minutes or less, **it will block all requests until the refresh is complete.**

Ideally, what I would love is this behavior for static(-ish) shared credentials that have a session token:

- Be able to set the expiration in ~/.aws/credentials and have the local container endpoint serve that if found.
- If not found, use a configurable setting (environment variable or somesuch injected into the container).
- Use 12.5 minutes (750) seconds.

But if all it did was the last bit, things would work for most cases.

**Comment by PettitWesley** [comment]
@dacut Thanks for doing that investigative work; super useful.

> Be able to set the expiration in ~/.aws/credentials and have the local container endpoint serve that if found.

This change would be hard to accomplish; the shared credentials file is so widely used. We'd have to change all the SDKs.

> If not found, use a configurable setting (environment variable or somesuch injected into the container).
> Use 12.5 minutes (750) seconds.

Realistically, this is the feature request we can accomplish. Would you be interested in submitting a pull request for this? Otherwise, we'll eventually get to it (though I can't promise when or if it will be soon).

**Comment by dacut** [comment]
Eventually (read: not in the context of this GitHub issue), this should go in ~/.aws/credentials because it **is** useful to the SDKs. Having a session token without an expiration date is kind of nonsensical. From what I can tell, the ones that I've used (Go, Python, C++, JavaScript) are properly coded to ignore unknown properties, so introducing new ones is a non-breaking change.

But that's for another day and a wider audience.

I'll see if I can get a pull request together that solves #2/#3. Same constraints on my end, though -- can't promise when. :-)

**Comment by PettitWesley** [comment]
@dacut agreed and sounds good 😎

**Comment by dacut** [comment]
Alright, I should have tomorrow free to work on a pull request for this. So don't start if you haven't already. :-)

**Comment by dacut** [comment]
@PettitWesley Not sure if you saw the pull request for this. It's over at https://github.com/awslabs/amazon-ecs-local-container-endpoints/pull/28. Ball's in your court when you get a chance, assuming you're not battening down the hatches for re:Invent releases and the like.
