### ISSUE TITLE
V1 Container Agent Introspection support

### ISSUE THREAD

**Issue by alejandrodnm** [awslabs/amazon-ecs-local-container-endpoints#33]
Are there plans to add the v1 endpoint? 

I know that it's very different in the way that it's expose to the tasks since it's the agent directly, but I have a use case for it and was wondering if there are plans to add it.

Thx

**Comment by PettitWesley** [comment]
Hey @alejandrodnm, at the moment we do not have definite plans to expand this tool. 

I agree that adding a simulated version of the V1 endpoint would be useful. Would you be interested in contributing this feature? It should be fairly straightforward- I think you can basically just re-use the code for the v2/v3 metadata endpoint. I know the `/v1/tasks` path in V1 returns multiple tasks, but for local use it could probably always just return a single task.
