### ISSUE TITLE
Support assuming roles in other accounts without CLI profiles

### ISSUE THREAD

**Issue by mbamber** [awslabs/amazon-ecs-local-container-endpoints#36]
When vending credentials using the `AWS_CREDENTIALS_RELATIVE_URI=role/<role_name>` environment variable, it is only possible to assume a role in the same account as the credentials in `~/.aws/credentials`. 

In line with a [recommended account structure](https://d0.awsstatic.com/aws-answers/AWS_Multi_Account_Security_Strategy.pdf) (Identity Account Structure) it is often the case that credentials on a developer machine are only for an identity account, but give permissions to assume roles in other accounts. This workflow does not work with this container, as the container can only assume roles in said identity account.

It would be good if this container could accept an optional environment variable for the account number in which the target role exists, and maybe even a corresponding role name that can be used for role discovery (via the `iam.GetRole()` SDK call)

**Comment by sonofachamp** [comment]
Hey @mbamber do your credentials in `~/.aws/credentials` have access to assume the role specified in `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`? Also, ensure you're using the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable instead of `AWS_CREDENTIALS_RELATIVE_URI`.

**Comment by mbamber** [comment]
@Sonofachamp - yes they do. But the role I want to assume is in a different account, and AFAIK I can’t assume a role in a different account?

**Comment by sonofachamp** [comment]
Cross-account assume role should work as long as permissions are set up correctly. Check out this [tutorials doc page](https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html) to see if this helps clarify the permissions necessary.

If it's still unclear please let us know. If you can provide your existing role configurations between the two accounts that would be helpful to troubleshoot further.

**Comment by mbamber** [comment]
I know the IAM permissions are correct, because I can run `aws sts assume-role` without issue. 

The problem is, how does this container know in which account to try and assume the role?

**Comment by sonofachamp** [comment]
Ah, I think I see what you're saying. It's only accepting `role_name` rather than `role_arn`. I'm not too familiar with this code base or the expected functionality that `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` should support, but I'll look into this.

**Comment by mbamber** [comment]
I’ve got a branch in my fork - but I want to do some testing before raising a PR - I’ll keep this issue updated though!

**Comment by mbamber** [comment]
Ok, I did some testing and it seems to work. 

The PR is above, please leave comments/feedback etc @sonofachamp  @PettitWesley 👍
