### ISSUE TITLE
Arm64 support via multi-arch images on dockerhub

### ISSUE THREAD

**Issue by scottmalkie** [awslabs/amazon-ecs-local-container-endpoints#45]
Hello!

Currently the dockerhub image is amd64 only.  Would it be possible to push a multi-arch (amd64 + arm64) manifest so as to support Graviton/Graviton2-based instances?  

Thanks!

**Comment by SoManyHs** [comment]
ARM images are now available on [DockerHub](https://hub.docker.com/r/amazon/amazon-ecs-local-container-endpoints/tags?page=1&ordering=last_updated)! 🎉

See: https://github.com/awslabs/amazon-ecs-local-container-endpoints/releases/tag/v1.4.0
